name: Build and Push Docker image to ECR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write # para autenticação OIDC

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-asume: arn:aws:iam::SEU_NUMERO_AWS:role/SUA_ROLE_GITHUB_ACTIONS
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/nihon-wakusei-frontend:latest
